/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Gracia Y Paz
 */
public class jPanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public jPanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_PrimerAlgoritmo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BT_SegundoAlgoritmo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BT_TercerAlgoritmo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LB_PrimerALgortmo = new javax.swing.JLabel();
        LB_SegundoAlgoritmo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BT_PrimerAlgoritmo.setText("Calcular");

        jLabel1.setText("Resultado primer algortimo");

        BT_SegundoAlgoritmo.setText("Calcular");

        jLabel2.setText("Resultado primer algortimo");

        BT_TercerAlgoritmo.setText("Calcular");

        jLabel3.setText("Resultado tercer algortimo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(BT_PrimerAlgoritmo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(LB_PrimerALgortmo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(LB_SegundoAlgoritmo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(BT_SegundoAlgoritmo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BT_TercerAlgoritmo)))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(LB_PrimerALgortmo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT_PrimerAlgoritmo)
                            .addComponent(BT_SegundoAlgoritmo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(LB_SegundoAlgoritmo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_TercerAlgoritmo)
                        .addGap(12, 12, 12)))
                .addGap(31, 31, 31))
        );

        BT_PrimerAlgoritmo.getAccessibleContext().setAccessibleName("BT_PrimerAlgoritmo");
        jLabel1.getAccessibleContext().setAccessibleName("");
        BT_SegundoAlgoritmo.getAccessibleContext().setAccessibleName("BT_SegundoAlgoritmo");
        jLabel2.getAccessibleContext().setAccessibleName("LB_SegundoAlgoritmo");
        BT_TercerAlgoritmo.getAccessibleContext().setAccessibleName("BT_TercerAlgoritmo");
        jLabel3.getAccessibleContext().setAccessibleName("LB_TercerAlgoritmo");
        jLabel3.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BT_PrimerAlgoritmo;
    public javax.swing.JButton BT_SegundoAlgoritmo;
    public javax.swing.JButton BT_TercerAlgoritmo;
    public javax.swing.JLabel LB_PrimerALgortmo;
    public javax.swing.JLabel LB_SegundoAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
